-- Initial schema for the task-management API.
--
-- Design notes:
--   * Primary keys are UUIDs generated by the application so a handler can log an
--     id before the INSERT round-trips.
--   * role / status / priority are real PostgreSQL ENUM types so the database
--     rejects invalid values instead of relying on application validation alone.
--     The labels are snake_case and match the Rust `#[sqlx(rename_all)]` /
--     `#[serde(rename_all)]` attributes exactly, which keeps the JSON wire
--     format, the Rust enums and the database in agreement.
--   * `updated_at` is maintained explicitly by the repository layer rather than
--     by a trigger, so every write path is visible in the Rust code.

CREATE TYPE user_role AS ENUM ('admin', 'staff');
CREATE TYPE task_status AS ENUM ('todo', 'in_progress', 'done');
CREATE TYPE task_priority AS ENUM ('low', 'medium', 'high');

CREATE TABLE users (
    id              UUID        PRIMARY KEY,
    full_name       TEXT        NOT NULL,
    -- Emails are lower-cased by the application before they reach the database,
    -- so a plain UNIQUE constraint is enough to make lookups case-insensitive.
    email           TEXT        NOT NULL UNIQUE,
    hashed_password TEXT        NOT NULL,
    role            user_role   NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE tasks (
    id             UUID          PRIMARY KEY,
    title          TEXT          NOT NULL,
    description    TEXT,
    status         task_status   NOT NULL DEFAULT 'todo',
    priority       task_priority NOT NULL DEFAULT 'medium',
    created_by_id  UUID          NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    assigned_to_id UUID          REFERENCES users (id) ON DELETE SET NULL,
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ   NOT NULL DEFAULT now()
);

-- GET /tasks/view-my-tasks filters on assigned_to_id on every cache miss.
CREATE INDEX tasks_assigned_to_id_idx ON tasks (assigned_to_id);
CREATE INDEX tasks_created_by_id_idx ON tasks (created_by_id);

-- A two-factor login challenge. `code_hash` is an Argon2id PHC string: the
-- one-time code itself is never persisted here in plain text.
CREATE TABLE login_challenges (
    id          UUID        PRIMARY KEY,
    user_id     UUID        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    code_hash   TEXT        NOT NULL,
    attempts    INTEGER     NOT NULL DEFAULT 0,
    expires_at  TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX login_challenges_user_id_idx ON login_challenges (user_id);

-- Local stand-in for an outbound mail transport. A row here represents an email
-- that a real deployment would have handed to SMTP. `verification_code` holds
-- the readable code because this row *is* the delivered message body -- see the
-- security note in README.md.
CREATE TABLE email_logs (
    id                 UUID        PRIMARY KEY,
    to_email           TEXT        NOT NULL,
    subject            TEXT        NOT NULL,
    body               TEXT        NOT NULL,
    verification_code  TEXT,
    login_challenge_id UUID        REFERENCES login_challenges (id) ON DELETE CASCADE,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX email_logs_recipient_created_at_idx
    ON email_logs (to_email, created_at DESC);
